variables:
  S3_BUCKET: kruta.link

stages:
  - deploy

s3-deploy:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp public s3://$S3_BUCKET --recursive